export const types = [
  { id: 1, type: 'fire' },
  { id: 2, type: 'flying' },
  { id: 3, type: 'bug' },
  { id: 4, type: 'dark' },
  { id: 5, type: 'dragon' },
  { id: 6, type: 'eletric' },
  { id: 7, type: 'grass' },
  { id: 8, type: 'poison' },
  { id: 9, type: 'water' },
  { id: 10, type: 'steel' },
  { id: 11, type: 'rock' },
  { id: 12, type: 'psychic' },
  { id: 13, type: 'normal' },
  { id: 14, type: 'ice' },
  { id: 15, type: 'ground' },
  { id: 16, type: 'ghost' },
  { id: 17, type: 'fighting' },
  { id: 18, type: 'fairy' },
  { id: 19, type: 'shadow' },
] as const;
